# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

sphinx:
   configuration: doc/source/conf.py

python:
  version: 3.9
  install:
    - requirements: doc/requirements.txt
